// src/components/SelectionStations.vue
<template>
  <div id="selection-stations">
    <div class="ui centered grid stackable ">
      <div v-for="(station,index) in loadedStations"
           :key="station.info.StationID">

        <div class="m-t-md">
          <div @click="onSegmentClick(station.info)"
               class="ui segment"
               :class="{active: station.info.StationID === selectedStation.info.StationID}">

            <span>{{station.info.StationName}}</span>
            <sui-icon class="space-left"
                      name="cancel"
                      @click="onCloseClick(station.info,
               $event)
               " />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { palette1 } from "../assets/chart/palettes.js";

export default {
  name: "SelectionStations",
  props: {
    loadedStations: Array,
    selectedStation: Object
  },
  data() {
    return {
      palette1
    };
  },
  methods: {
    onCloseClick: function(station, event) {
      event.stopPropagation();
      // console.log("station.StationID", station.StationID);
      this.$store.dispatch("data/REMOVE_STATION", station.StationID);
      this.$ga.event("Remove", "Station", station.StationName);
    },
    onSegmentClick(station) {
      this.$store.commit("data/SELECT_STATION", station.StationID);
      this.$ga.event("Select", "Station", station.StationName);
    }
  }
};
</script>

<style lang="scss" scoped>
@import "../style/style.scss";

#selection-stations {
  .space-left {
    margin-left: 0.5rem;
  }
  .active {
    font-weight: bold;
    color: $offWhite;
    background: $primaryColor;
  }
  div.ui.segment {
    padding: 0.5rem;
  }
}
</style>

// src/components/SelectionStations/index.jsx
import React from 'react'
import { Icon, Segment, Grid } from 'semantic-ui-react'
import useDataStore from '../../store/useDataStore'
import './SelectionStations.scss'

const SelectionStations = ({ loadedStations, selectedStation }) => {
  const dataStore = useDataStore()

  const onCloseClick = (station, event) => {
    event.stopPropagation()
    dataStore.removeStation(station.id)
  }

  const onSegmentClick = (station) => {
    dataStore.selectStation(station.id)
  }

  if (!selectedStation) return null

  return (
    <div id="selection-stations">
      <Grid stackable centered>
        {loadedStations.map((station) => (
          <Grid.Column key={station.info.StationID} width={4}>
            <div className="m-t-md">
              <Segment
                onClick={() => onSegmentClick(station.info)}
                className={station.info.id === selectedStation.info.id ? 'active' : ''}
              >
                <span>{station.info.StationName}</span>
                <Icon
                  className="space-left"
                  name="cancel"
                  onClick={(e) => onCloseClick(station.info, e)}
                />
              </Segment>
            </div>
          </Grid.Column>
        ))}
      </Grid>
    </div>
  )
}

export default SelectionStations
