// src/components/SelectionWrapper.vue
<template>
  <div>
    <div class="">
      <sui-message v-if="ui.errorMsg.selection"
                   color="red">
        <p>{{ui.errorMsg.selection}}</p>
      </sui-message>
      <div class="ui two column centered grid"
           id="selection-boxes">
        <div class="column"
             id="step-0">
          <multiselect v-model="selectedFork"
                       id="select-1"
                       label="fullName"
                       placeholder="Select a Fork"
                       @input="forkUpdated"
                       track-by="fullName"
                       :options="forkOptions"></multiselect>
        </div>
        <div class="column"
             id="step-2">
          <multiselect :options="sortedStationOptions"
                       id="select-2"
                       placeholder="select a station"
                       label="label"
                       @input="fetchStationData"
                       track-by="label"
                       v-model="selectedStation"></multiselect>
        </div>
      </div>
      <div class="ui grid">
        <div class="column"
             id="step-3">
          <selection-station-map v-if="stationOptions"
                                 id='station-map'
                                 :stations="stationOptions"></selection-station-map>
        </div>
      </div>
      <div v-if="ui.isLoading">
        <Loader />
      </div>
      <div id="step-4"
           class="m-b-lg">
        <selection-stations :loadedStations="data.loadedStations"
                            :selectedStation="data.selectedStation"></selection-stations>
      </div>
      <div id="step-6"
           v-if="ui.showYearSelection">
        <!-- only show year selection for line graphs etc not for boxplots -->
        <div v-if="!selection.singleYearSelection">
          <selection-years-range v-if="selection.selectionRange"
                                 :data="data"
                                 :selection="selection"></selection-years-range>
        </div>
        <div v-else>
          <selection-year-single :data="data"
                                 :selection="selection"></selection-year-single>
        </div>
      </div>
      <div id="step-5"
           v-if="data.loadedStations.length > 0">
        <selection-params></selection-params>
      </div>
    </div>
  </div>
</template>

<script>
import Multiselect from "vue-multiselect";
import SelectionStations from "./SelectionStations";
import SelectionYearsRange from "./SelectionYearsRange";
import SelectionYearSingle from "./SelectionYearSingle";
import SelectionParams from "./SelectionParams";
import SelectionStationMap from "./SelectionStationMap";
import Loader from "./Loader";

import {
  calculateForksForSelection,
  calculateStationsForSelection
} from "../utils/selectionUtils.js";

import { mapState } from "vuex";
import sortBy from "lodash/sortBy";

export default {
  name: "SelectionWrapper",
  props: {
    stations: Array
  },
  components: {
    Multiselect,
    Loader,
    SelectionStations,
    SelectionParams,
    SelectionYearsRange,
    SelectionYearSingle,
    SelectionStationMap
  },
  data() {
    return {
      selectedStation: null,
      selectedFork: null,
      stationOptions: [],
      forkOptions: []
    };
  },
  computed: {
    ...mapState({
      ui: state => state.ui,
      selection: state => state.selection,
      data: state => state.data
    }),
    sortedStationOptions: function() {
      return sortBy(this.stationOptions, o => o.label);
    }
  },
  mounted() {
    // Sets allStations in selection vuex but also parses allForks, allWaterbodies etc
    this.$store.dispatch("selection/SET_ALL_STATIONS", this.stations);
    // Initialize forks, streams and stations
    this.forkOptions = calculateForksForSelection(this.selection.allForks);
    this.stationOptions = calculateStationsForSelection(
      this.stations,
      null,
      null
    );
  },
  methods: {
    forkUpdated: function() {
      console.log("this.selectedFork", this.selectedFork);
      // selected allForks
      if (!this.selectedFork.value) {
        this.stationOptions = calculateStationsForSelection(
          this.stations,
          null
        );
      } else {
        // selected an actual Fork
        this.stationOptions = calculateStationsForSelection(
          this.stations,
          this.selectedFork
        );
      }
      this.selectedStation = null;
    },

    fetchStationData: function(station) {
      this.$store.dispatch("data/FETCH_STATION_DATA", station.value);
    }
  }
};
</script>

<style>
#selection-boxes > div {
  z-index: 100000;
}
#station-map {
}
</style>

// src/components/SelectionWrapper/index.jsx
import React, { useMemo } from 'react'
import { Message, Grid } from 'semantic-ui-react'
import Select from 'react-select'
import SelectionStationMap from '../SelectionStationMap'
import SelectionStations from '../SelectionStations'
import SelectionYearsRange from '../SelectionYearsRange'
import SelectionYearSingle from '../SelectionYearSingle'
import SelectionParams from '../SelectionParams'
import Loader from '../Loader'
import useUiStore from '../../store/useUiStore'
import useDataStore from '../../store/useDataStore'
import useSelectionStore from '../../store/useSelectionStore'
import { calculateStationsForSelection, calcStationOption } from '../../utils/selectionUtils'
import sortBy from 'lodash/sortBy'
import './SelectionWrapper.scss'

const SelectionWrapper = ({ stations, safeOptions, projects }) => {
  const ui = useUiStore()
  const data = useDataStore()
  const selection = useSelectionStore()

  const stationOptions = useMemo(() => calculateStationsForSelection(stations), [stations])
  const sortedStationOptions = useMemo(() => sortBy(stationOptions, (o) => o.label), [stationOptions])

  const selectedProjectOption = projects?.find(p => p.ProjectID === data.activeProject?.ProjectID) || null

  const currentSelectedStationOption = useMemo(() => {
    if (data.selectedStation && data.selectedStation.info && data.selectedStation.info.id) {
      return calcStationOption(data.selectedStation.info)
    }
    return null
  }, [data.selectedStation])

  const handleProjectChange = (option) => {
    data.setActiveProject(option)
    selection.setProject(option)
    data.selectStation(null)
    data.resetStations()
    selection.clearParam()
  }

  const handleStationChange = (option) => {
    if (option) {
      console.log('Fetch station data', option.value)
    }
  }

  return (
    <div id="selection-wrapper">
      {ui.errorMsg.selection && (
        <Message color="red">
          <p>{ui.errorMsg.selection}</p>
        </Message>
      )}
      <Grid id="step-3">
        <Grid.Column>
          {stationOptions && (
            <SelectionStationMap stations={stationOptions} safeOptions={safeOptions} />
          )}
        </Grid.Column>
      </Grid>

      {!safeOptions && (
        <>
          <Grid centered columns={2} className={ui.showInfoModal ? 'hide-multiselect' : ''} id="selection-boxes">
            <Grid.Column id="step-0">
              <Select
                options={projects}
                getOptionLabel={(o) => o.Name}
                getOptionValue={(o) => o.ProjectID}
                value={selectedProjectOption}
                onChange={handleProjectChange}
                placeholder="Select a Project"
              />
            </Grid.Column>
            <Grid.Column id="step-2">
              <Select
                options={sortedStationOptions}
                value={currentSelectedStationOption}
                onChange={handleStationChange}
                placeholder="Select a Station"
              />
            </Grid.Column>
          </Grid>

          {ui.isLoading && <Loader />}

          <div id="step-4" className="m-b-lg">
            <SelectionStations loadedStations={data.loadedStations} selectedStation={data.selectedStation} />
          </div>

          {ui.showYearSelection && (
            <div id="step-6">
              {!selection.singleYearSelection ? (
                selection.selectionRange && <SelectionYearsRange data={data} selection={selection} />
              ) : (
                <SelectionYearSingle data={data} selection={selection} />
              )}
            </div>
          )}

          {data.loadedStations.length > 0 && (
            <div id="step-5">
              <SelectionParams />
            </div>
          )}
        </>
      )}
    </div>
  )
}

export default SelectionWrapper
