// src/components/SelectionParams.vue
<template>
  <div id="selection-params"
       class="m-t-xl ui segment">
    <div class="centered-buttons ui ">
      <sui-button-group basic
                        v-for="p in allParams"
                        :key="p">
        <sui-button @click="selectParam(p, $event)"
                    compact
                    :class="{active: p === selection.activeParam}">
          {{parameterName(p)}}
        </sui-button>
      </sui-button-group>
      <div class="centered-buttons ui">
        <div v-if="canHaveSecondaryParam()"
             class="p-t-md">
          <sui-divider></sui-divider>
          <small>
            <b>Secondary Parameter: </b>
          </small>
          <br/>
          <sui-button-group basic
                            class="secondary-param"
                            v-for="(p2,index) in allParams"
                            :key="index">
            <sui-button v-if="p2 !== selection.activeParam"
                        @click="selectSecondaryParam(p2, $event) "
                        compact
                        :class="{active: p2===selection.secondaryParam}
            "> {{parameterName(p2)}}
            </sui-button>
          </sui-button-group>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";
import flatten from "lodash/flatten";
import uniq from "lodash/uniq";
import names from "../assets/parameterNames.js";

export default {
  name: "SelectionParams",
  computed: {
    ...mapState({
      selection: state => state.selection,
      data: state => state.data
    }),
    allParams: function() {
      // Gets all params of all loaded stations
      let temp = this.data.loadedStations.map(s => s.meta.params);
      temp = uniq(flatten(temp));
      // Remove stupid null_null value
      const nullRegex = RegExp("null");
      temp = temp.filter(t => !nullRegex.test(t));
      // remove date
      const dateRegex = RegExp("date");
      temp = temp.filter(t => !dateRegex.test(t));
      // return alphabetically sorted
      return temp.sort();
    }
  },
  methods: {
    parameterName: function(p) {
      try {
        return names[p].text;
      } catch (err) {
        return "";
      }
    },
    canHaveSecondaryParam: function() {
      if (
        // only LINE charts work with secondary param
        this.selection.chartType === "LINE_MULTI" ||
        this.selection.chartType === "LINE_SINGLE"
      ) {
        if (this.data.loadedStations.length === 1) {
          // only allows secondaryParam if only one station is selected
          return true;
        }
      }
      return false;
    },
    selectParam: function(param, $event) {
      this.$store.commit("data/GENERATE_KEY");
      if (!$event.shiftKey) {
        this.$store.commit("selection/SELECT_ACTIVE_PARAM", param);
        this.$ga.event("Select", "Param  ", param);
      }
    },
    selectSecondaryParam: function(param) {
      if (param === this.selection.secondaryParam) {
        this.$store.commit("selection/SELECT_SECONDARY_PARAM", null);
      }
      // param is different from activeParam
      else if (param !== this.selection.activeParam) {
        this.$store.commit("selection/SELECT_SECONDARY_PARAM", param);
        this.$ga.event("Select", "Secondary Param  ", param);
      }
    }
  }
};
</script>

<style lang="scss" scoped>
@import "../style/_variables.scss";

#selection-params {
  .centered-buttons {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
  }
  // .ui.button {
  //   background: $darkWhite;
  // }
  .ui.buttons > button {
    // background: $offWhite;
    &.active {
      background: lighten($lightGrey, 5%);
      box-shadow: inset 3 0 3px #000000;
    }
    &.secondaryActive {
      background: lighten($lightGrey, 10%) !important;
      box-shadow: inset 3 0 3px #000000;
      color: $primaryColor !important;
    }
  }
  div.secondary-param {
    button {
      font-size: 0.85srem;
    }
  }
}
</style>

// src/components/SelectionParams/index.jsx
import React, { useMemo, useEffect } from 'react'
import { Button } from 'semantic-ui-react'
import useSelectionStore from '../../store/useSelectionStore'
import useDataStore from '../../store/useDataStore'
import names from '../../assets/parameterNames'
import uniq from 'lodash/uniq'
import flatten from 'lodash/flatten'
import './SelectionParams.scss'

const SelectionParams = () => {
  const selectionStore = useSelectionStore()
  const dataStore = useDataStore()

  const allParams = useMemo(() => {
    let temp = dataStore.loadedStations.map(s => s.meta.params)
    temp = uniq(flatten(temp))
    const nullRegex = /null/
    const dateRegex = /date/
    const obsRegex = /FieldObs_/
    const fieldRegex = /field_/

    temp = temp.filter(t =>
      !nullRegex.test(t) &&
      !dateRegex.test(t) &&
      !obsRegex.test(t) &&
      !fieldRegex.test(t)
    )
    return temp.sort()
  }, [dataStore.loadedStations])

  useEffect(() => {
    if (!selectionStore.activeParam && allParams.length > 0) {
      const defaultParam = allParams.includes('H2O_Temp') ? 'H2O_Temp' : allParams[0]
      selectionStore.setActiveParam(defaultParam)
    }
  }, [allParams, selectionStore])

  const allSecondaryParams = useMemo(() => {
    return allParams.filter(p => p !== selectionStore.activeParam)
  }, [allParams, selectionStore.activeParam])

  const parameterName = (p) => names[p]?.text || p.replace('H2O_', '')

  const canHaveSecondaryParam = () => {
    if (selectionStore.chartType === 'LINE_MULTI' || selectionStore.chartType === 'LINE_SINGLE') {
      if (dataStore.loadedStations.length === 1 && allParams.length > 1) {
        return true
      }
    }
    return false
  }

  const selectParam = (param) => {
    dataStore.generateKey()
    selectionStore.setActiveParam(param)
  }

  const selectSecondaryParam = (param) => {
    if (param === selectionStore.secondaryParam) {
      selectionStore.setSecondaryParam(null)
    } else {
      selectionStore.setSecondaryParam(param)
    }
  }

  return (
    <div id="selection-params">
      <small>
        <b>{canHaveSecondaryParam() ? 'Primary Parameter: ' : 'Parameter: '}</b>
      </small>
      <br />
      <div className="flex-row">
        {allParams.map(p => (
          <div key={p}>
            <Button
              onClick={() => selectParam(p)}
              active={p === selectionStore.activeParam}
              fluid
            >
              {parameterName(p)}
            </Button>
          </div>
        ))}
      </div>
      {canHaveSecondaryParam() && (
        <div className="m-t-md">
          <small><b>Secondary Parameter: </b></small>
          <br />
          <div className="flex-row secondary-param-row">
            {allSecondaryParams.map(p2 => (
              <div key={p2}>
                <Button
                  onClick={() => selectSecondaryParam(p2)}
                  active={p2 === selectionStore.secondaryParam}
                  fluid
                  size="small"
                >
                  {parameterName(p2)}
                </Button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

export default SelectionParams
