// src/components/OrganizationList/index.jsx
import React from 'react'
import organizations from '../../assets/organizations'
import OrganizationCard from '../OrganizationCard'

const OrganizationList = () => {
  return (
    <div className="ui centered grid stackable">
      {organizations.map((org) => (
        <div key={org.abbreviation} className="four wide computer six wide tablet column">
          <OrganizationCard org={org} />
        </div>
      ))}
    </div>
  )
}

export default OrganizationList

// src/components/OrganizationList.vue
<template>
  <div class="ui centered grid stackable">
    <div v-for="org in organizations"
         :key="org.abbreviation"
         class="four wide computer six wide tablet  column">
      <organization-card :org="org"></organization-card>
    </div>
  </div>
</template>

<script>
import organizations from "../assets/organizations.js";
import OrganizationCard from "./OrganizationCard";

export default {
  name: "OrganizationsCards",
  components: {
    OrganizationCard
  },
  data() {
    return {
      organizations
    };
  }
};
</script>

<style>
</style>
