// src/components/OrgPageIntro/index.jsx
import React from 'react'
import { Card, Image } from 'semantic-ui-react'
import './OrgPageIntro.scss'

const OrgPageIntro = ({ info }) => {
  return (
    <div id="org-page-intro">
      <Card.Content className="card-header">
        <h2 className="ui center aligned icon header">{info.Name}</h2>
      </Card.Content>
      <div className="spacer">
        <Image src={info.Logo} size="small" floated="left" />
        <p>{info.AgencyDescr}</p>
      </div>
    </div>
  )
}

export default OrgPageIntro

// src/components/OrgPageIntro.vue
<template>
  <div id="org-page-intro">
    <sui-card-content class="card-header">
      <h2 class="ui center aligned icon header">{{info.Name}}</h2>
      <!-- <h2 class="ui center aligned icon header">{{info.tagLine}}</h2> -->
    </sui-card-content>
    <div class="spacer">
      <sui-image :src="info.Logo"
                 size="small"
                 floated="left" />
      <!-- <h5>{{info.missionStatement}}</h5> -->
      <!-- <sui-divider></sui-divider> -->
      <p>{{info.AgencyDescr}}</p>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    info: Object
  },
  mounted() {
    //console.log("OrgIntro", this.info)
  }
};
</script>

<style lang="scss" scoped>
@import "../style/style.scss";
#org-page-intro div.card-header {
  padding: 0.2rem;
  background: $primaryColor;
  background: linear-gradient(
    45deg,
    rgba(0, 132, 203, 1) 0%,
    $lightPrimaryColor 100%
  );
  border-bottom: 3px solid $secondaryColor;
  h1,
  h2 {
    font-weight: normal;
    text-align: center;
    color: $offWhite;
    margin: 0.2rem;
  }
}
.spacer {
  margin: 1rem;
}
</style>
