// src/components/OrgPageOverviewMap/index.jsx
import React, { useEffect, useMemo } from 'react'
import { MapContainer, TileLayer, LayersControl, GeoJSON } from 'react-leaflet'
import { useParams } from 'react-router-dom'
import useOrganizationStore from '../../store/useOrganizationStore'
import { tileProviders } from '../../assets/tileProviders'
import { tribStyleWithName, tribStyleWithoutName } from '../../assets/constants'
import './OrgPageOverviewMap.scss'

const OrgPageOverviewMap = () => {
  const { org } = useParams()
  const organizationStore = useOrganizationStore()
  const ws = organizationStore.watershed

  useEffect(() => {
    if (org) {
      organizationStore.fetchOrganizationWatershed(org)
    }
  }, [org])

  const bounds = useMemo(() => {
    if (ws?.catchmentInfo?.shape?.coordinates?.[0]) {
      const coords = ws.catchmentInfo.shape.coordinates[0]
      const lats = coords.map(c => c[1])
      const lngs = coords.map(c => c[0])
      return [[Math.min(...lats), Math.min(...lngs)], [Math.max(...lats), Math.max(...lngs)]]
    }
    return null
  }, [ws])

  const upstreamOptions = {
    onEachFeature: (feature, layer) => {
      const name = feature.geometry.properties.name || `comid: ${feature.geometry.properties.comid}`
      layer.bindTooltip(name, { sticky: true })
    },
    style: (feature) => feature.geometry.properties.name ? tribStyleWithName : tribStyleWithoutName
  }

  if (!bounds) return <div id="map-skeleton" className="map-height">Loading Watershed...</div>

  return (
    <div className="m-t-md m-b-md">
      <MapContainer bounds={bounds} id="map" className="map-height" scrollWheelZoom={false}>
        <LayersControl position="topright">
          {tileProviders.map((tp) => (
            <LayersControl.BaseLayer key={tp.name} name={tp.name} checked={tp.visible}>
              <TileLayer url={tp.url} attribution={tp.attribution} />
            </LayersControl.BaseLayer>
          ))}
        </LayersControl>
        <GeoJSON data={ws.catchmentInfo.shape} />
        {ws.upstreamInfo.paths.map((ut, i) => (
          <GeoJSON key={`up-${i}`} data={ut.shape} {...upstreamOptions} />
        ))}
      </MapContainer>
      <div className="wsm-info">
        <p id="inside-map">
          For a more interactive view of the whole watershed go to{' '}
          <a href={`https://watershedmap.org/${org}`} target="_blank" rel="noopener noreferrer">
            watershedmap.org
          </a>
        </p>
      </div>
    </div>
  )
}

export default OrgPageOverviewMap

// src/components/OrgPageOverviewMap.vue
<template>
  <div class="m-t-lg m-b-xl map-height"
       v-if="bounds">
    <l-map :bounds="bounds"
           id="map"
           ref="map">
      <l-tile-layer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></l-tile-layer>
      <!-- Catchment outline -->
      <l-geo-json ref='outline'
                  :geojson="ws.catchmentInfo.shape"></l-geo-json>
      <l-geo-json v-for="(ut,index) in ws.upstreamInfo.paths"
                  :key="index"
                  :geojson="ut.shape"
                  ref="upstreamRef"
                  :options="upstreamOptions">
      </l-geo-json>
    </l-map>
    <p id="inside-map">For a more interactive view of the whole watershed go to
      <a :href="externalLink"
         target="_blank
         ">watershedmap.org</a>
    </p>
  </div>
</template>

<script>
import { LMap, LTileLayer, LGeoJson, LMarker } from "vue2-leaflet";
import {
  tribStyleWithName,
  tribStyleWithoutName
} from "../assets/constants.js";
import geolib from "geolib";

import { mapState } from "vuex";

export default {
  name: "OrgPageOverviewMap",
  components: {
    LMap,
    LTileLayer,
    LGeoJson,
    LMarker
  },
  data() {
    return {
      url: "http://{s}.tile.osm.org/{z}/{x}/{y}.png"
    };
  },
  mounted() {
    // Fetch organizations watershed
    this.$store.dispatch(
      "organization/FETCH_ORGANIZATION_WATERSHED",
      this.$route.params.org
    );
  },
  computed: {
    ...mapState({
      ws: state => state.organization.watershed
    }),
    // Bounds of map from watershed
    externalLink: function() {
      return `https://watershedmap.org/${this.$route.params.org}`;
    },
    bounds: function() {
      if (this.ws && this.ws.bounds) {
        // Calculate new bounds
        let shape = this.ws.catchmentInfo.shape.coordinates[0];
        let nb = geolib.getBounds(shape);
        return L.latLngBounds(
          L.latLng(nb.maxLat, nb.maxLng),
          L.latLng(nb.minLat, nb.minLng)
        );
      } else {
        // console.log('this.wsbounds',this.ws.bounds)
        return null;
      }
    },
    upstreamOptions: function() {
      let oef = {
        onEachFeature: (feature, layer) => {
          layer.on({
            mouseover: e => {
              var layer = e.target;
              if (e.target.feature.geometry.properties.name) {
                layer
                  .bindTooltip(`${e.target.feature.geometry.properties.name}`, {
                    sticky: true
                  })
                  .openTooltip();
              } else {
                layer
                  .bindTooltip(
                    `comid: ${e.target.feature.geometry.properties.comid}`,
                    { sticky: true }
                  )
                  .openTooltip();
              }
            },
            mouseout: e => {
              e.target.closePopup();
            }
          });
        },
        style: feature => {
          if (feature.geometry.properties.name) {
            return tribStyleWithName;
          } else {
            return tribStyleWithoutName;
          }
        }
      };
      return { ...oef };
    }
  }
};
</script>

<style lang="scss">
.map-height {
  height: 500px;
  border-radius: 6px;
  box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.05);
}
#inside-map {
  z-index: 100000;
}
</style>
