// src/components/SelectionYearsRange/index.jsx
import React from 'react'
import Slider from 'rc-slider'
import 'rc-slider/assets/index.css'
import useSelectionStore from '../../store/useSelectionStore'

const SelectionYearsRange = ({ data, selection }) => {
  const selectionStore = useSelectionStore()

  const handleDragEnd = (values) => {
    selectionStore.setYearRange(values)
  }

  if (!data.startYear) return null

  return (
    <div className="m-t-lg m-b-lg">
      <Slider
        range
        min={data.startYear}
        max={data.endYear}
        defaultValue={selection.selectionRange || [data.startYear, data.endYear]}
        onAfterChange={handleDragEnd}
        marks={Object.fromEntries(
          Array.from({ length: data.endYear - data.startYear + 1 }, (_, i) => [
            data.startYear + i,
            (data.startYear + i).toString()
          ])
        )}
        step={1}
      />
    </div>
  )
}

export default SelectionYearsRange

// src/components/SelectionYearsRange.vue
<template>
  <div v-if="data.startYear"
       class="m-t-lg m-b-lg">

    <vue-slider v-bind="settings"
                @drag-end="dragEnd"
                v-model="selection.selectionRange"></vue-slider>
  </div>
</template>

<script>
import vueSlider from "vue-slider-component";

export default {
  name: "SelectionYearsRange",
  components: { vueSlider },
  props: { data: Object, selection: Object },
  data() {
    return {
      range: [
        this.selection.selectionRange[0],
        this.selection.selectionRange[1]
      ]
    };
  },
  computed: {
    min: function() {
      return this.data.startYear;
    },
    max: function() {
      return this.data.endYear;
    },
    settings: function() {
      return {
        min: this.min,
        max: this.max,
        interval: 1,
        piecewise: true,
        piecewiseLabel: true
      };
    }
  },

  methods: {
    dragEnd: function(v) {
      this.$store.commit("selection/SET_YEAR_RANGE", v.getValue());
    }
  }
};
</script>

<style>
</style>
