// src/components/StationInfoModal/index.jsx
import React, { useState, useEffect } from 'react'
import { Modal, Header, Grid, Image } from 'semantic-ui-react'
import axios from 'axios'
import useUiStore from '../../store/useUiStore'
import useOrganizationStore from '../../store/useOrganizationStore'
import { CLOUDINARY_URL } from '../../assets/constants'
import forkNames from '../../assets/riverForkNames'
import './StationInfoModal.scss'

const StationInfoModal = () => {
  const ui = useUiStore()
  const organization = useOrganizationStore()
  const [imgUrl, setImgUrl] = useState(null)
  const [imgError, setImgError] = useState(false)
  const [imgLoading, setImgLoading] = useState(true)

  const station = ui.showInfoModalStation
  const organizationName = organization.activeOrganization?.AgencyCode

  useEffect(() => {
    if (station && organizationName) {
      const url = `${CLOUDINARY_URL}/${organizationName}_1/${station.StationID}.jpg`
      setImgLoading(true)
      setImgError(false)

      axios.get(url, { responseType: 'blob' })
        .then(res => {
          const reader = new window.FileReader()
          reader.readAsDataURL(res.data)
          reader.onload = () => {
            setImgUrl(reader.result)
            setImgLoading(false)
          }
        })
        .catch(() => {
          setImgLoading(false)
          setImgError(true)
        })
    }
  }, [station, organizationName])

  const getFork = () => {
    if (!station) return ''
    return forkNames[station.ForkTribGroup] || station.ForkTribGroup
  }

  const handleClose = () => {
    ui.toggleStationInfoModal(null)
  }

  if (!station) return null

  return (
    <Modal open={ui.showInfoModal} onClose={handleClose} size="large" closeIcon>
      <Modal.Header>{station.StationName}</Modal.Header>
      <Modal.Content scrolling>
        <Grid>
          <Grid.Row columns={2}>
            <Grid.Column>
              <b>Waterbody: </b> <span>{station.LocalWaterbody}</span>
            </Grid.Column>
            <Grid.Column>
              <b>Watershed: </b> <span>{station.LocalWatershed}</span>
            </Grid.Column>
            <Grid.Column>
              <b>Riverfork: </b> <span>{getFork()}</span>
            </Grid.Column>
            <Grid.Column>
              <b>Station ID: </b> <span>{station.StationID}</span>
            </Grid.Column>
            <Grid.Column>
              <b>Latitude: </b> <span>{station.TargetLat}</span>
            </Grid.Column>
            <Grid.Column>
              <b>Longitude: </b> <span>{station.TargetLong}</span>
            </Grid.Column>
          </Grid.Row>
          <Grid.Row>
            <Grid.Column textAlign="center">
              {imgLoading && <div className="img-placeholder">Loading image...</div>}
              {imgUrl && <Image src={imgUrl} className="station-image" centered />}
              {imgError && <div className="img-error-msg">No image available for the site</div>}
            </Grid.Column>
          </Grid.Row>
        </Grid>
      </Modal.Content>
    </Modal>
  )
}

export default StationInfoModal

// src/components/StationInfoModal.vue
<template>
  <modal name="station-info-modal"
         scrollable
         height="auto"
         width="50%"
         @closed="modalClosed">
    <div id="station-info-modal">
      <h3 is="sui-header"
          textAlign="center">{{ui.showInfoModalStation.StationName}}</h3>
      <sui-grid>
        <sui-grid-row :columns="2">
          <sui-grid-column>
            <b>Waterbody: </b>
            <span>{{ui.showInfoModalStation.LocalWaterbody}}</span>
          </sui-grid-column>
          <sui-grid-column>
            <b>Watershed: </b>
            <span>{{ui.showInfoModalStation.LocalWatershed}}</span>
          </sui-grid-column>
          <sui-grid-column>
            <b>Riverfork: </b>
            <span>{{fork()}}</span>
          </sui-grid-column>
          <sui-grid-column>
            <b>Station ID: </b>
            <span>{{ui.showInfoModalStation.StationID}}</span>
          </sui-grid-column>
          <sui-grid-column>
            <b>Latitude: </b>
            <span>{{ui.showInfoModalStation.TargetLat}}</span>
          </sui-grid-column>
          <sui-grid-column>
            <b>Longitude: </b>
            <span>{{ui.showInfoModalStation.TargetLong}}</span>
          </sui-grid-column>
        </sui-grid-row>

        <img id="station-image" />
        <skeleton v-if="imgLoading"
                  id="img-placeholder"></skeleton>
        <!-- <sui-image :src="imageURL"
                 fluid /> -->
      </sui-grid>
      <div v-if="imgError"
           class="img-error-msg"> <b>No image available for the site</b></div>
    </div>
  </modal>
</template>

<script>
import Skeleton from "./Skeleton";
import forkNames from "../assets/riverForkNames.js";
import { CLOUDINARY_URL } from "../assets/constants.js";
import { mapState } from "vuex";
import axios from "axios";

export default {
  name: "StationInfoModal",
  components: {
    Skeleton
  },
  props: {
    station: Object
  },
  data() {
    return {
      imgLoading: true,
      imgError: false
    };
  },
  mounted() {
    this.showModal();
    axios
      .get(this.imageURL, { responseType: "blob" })
      .then(res => {
        let imageElement = document.getElementById("station-image");
        let reader = new window.FileReader();
        reader.readAsDataURL(res.data);
        this.imgLoading = false;
        reader.onload = function() {
          let imageDataUrl = reader.result;
          imageElement.setAttribute("src", imageDataUrl);
          imageElement.style.height = "400px";
          imageElement.style.width = "auto";
          imageElement.style.maxWidth = "100%";
          imageElement.style.padding = "0";
          imageElement.style.boxShadow = "0px 7px 24px 3px rgba(0,0,0,0.25)";
          imageElement.style.borderRadius = "5px";
          imageElement.style.margin = "0 auto";
        };
      })
      .catch(err => {
        this.imgLoading = false;
        this.imgError = true;
      });
  },
  computed: {
    ...mapState({
      organization: state => state.organization,
      ui: state => state.ui,
      data: state => state.data
    }),
    organizationName: function() {
      return this.organization.activeOrganization;
    },
    imageURL: function() {
      let str = `${CLOUDINARY_URL}/${this.organizationName}/${
        this.ui.showInfoModalStation.StationID
      }.jpg`;
      return str;
    }
  },
  watch: {
    ui: {
      handler: function(val, oldVal) {
        if (val.showInfoModal) {
          this.showModal();
        } else {
          this.hideModal();
        }
      },
      deep: true
    }
  },
  methods: {
    fork: function() {
      if (forkNames[this.ui.showInfoModalStation.ForkTribGroup]) {
        return forkNames[this.ui.showInfoModalStation.ForkTribGroup];
      } else {
        return this.ui.showInfoModalStation.ForkTribGroup;
      }
    },
    modalClosed() {
      this.$store.commit("ui/TOGGLE_STATION_INFO_MODAL", null);
    },
    showModal() {
      this.$modal.show("station-info-modal");
    },
    hideModal() {
      this.$modal.hide("station-info-modal");
    }
  }
};
</script>

<style lang="scss">
@import "../style/style.scss";
#station-info-modal {
  margin: 2rem;
  z-index: 3000;
  .column {
    margin: 0.25rem 0;
  }
}
#img-placeholder {
  height: 400px;
  width: 100%;
}
#station-image {
  height: 0;
}
.v--modal-overlay {
  background: rgba(0, 0, 0, 0.6);
}
.v--modal.v--modal-box {
  background: $midWhite;
}
.img-error-msg {
  text-align: center;
  margin-top: 1rem;
}
</style>
