// src/components/ChartsTabs.vue
<template>
  <div id="chart-tabs">

    <sui-tab @change="handleChange">
      <sui-tab-pane title="multi year line">
        <charts-line-chart class="chart chart-spacer"
                           :selection="selection"
                           :data="data"></charts-line-chart>
      </sui-tab-pane>
      <sui-tab-pane title="single year line">
        <charts-line-chart class="chart chart-spacer"
                           :selection="selection"
                           :data="data"></charts-line-chart>
      </sui-tab-pane>
      <sui-tab-pane title="box plot">
        <charts-box-chart-per-station class="chart chart-spacer"
                                      :selection="selection"
                                      :data="data"></charts-box-chart-per-station>
      </sui-tab-pane>
      <sui-tab-pane title="box plot per month">
        <charts-box-chart-per-month class="chart chart-spacer"
                                    :selection="selection"
                                    :data="data"></charts-box-chart-per-month>
      </sui-tab-pane>
    </sui-tab>
  </div>
</template>

<script>
import ChartsLineChart from "./ChartsLineChart";
import ChartsBoxChartPerStation from "./ChartsBoxChartPerStation";
import ChartsBoxChartPerMonth from "./ChartsBoxChartPerMonth";

export default {
  name: "ChartTabs",
  components: {
    ChartsLineChart,
    ChartsBoxChartPerStation,
    ChartsBoxChartPerMonth
  },
  props: { data: Object, selection: Object },
  methods: {
    handleChange: function(e, activePane, index) {
      if (index === 0) {
        // multi year line
        this.$store.commit("selection/SELECT_SINGLE_YEAR", false);
        this.$store.commit("selection/SET_CHART_TYPE", "LINE_MULTI");
        this.$store.commit("selection/SET_YEAR_RANGE", [
          this.data.startYear,
          this.data.endYear
        ]);
        this.$store.commit("ui/SHOW_YEAR_SELECTION", true);
        this.$ga.event("Select", "Chart-Type", "mutli-year line");
      }
      if (index === 1) {
        // single year line
        this.$store.commit("selection/SELECT_SINGLE_YEAR", true);
        this.$store.commit("selection/SET_CHART_TYPE", "LINE_SINGLE");
        this.$store.commit("selection/SET_YEAR_RANGE", [
          this.data.endYear,
          this.data.endYear
        ]);
        this.$store.commit("ui/SHOW_YEAR_SELECTION", true);
        this.$ga.event("Select", "Chart-Type", "single-year line");
      }
      if (index === 2) {
        // for boxplots don't show year selection
        this.$store.commit("selection/SET_CHART_TYPE", "BOX");
        this.$store.commit("ui/SHOW_YEAR_SELECTION", false);
        this.$ga.event("Select", "Chart-Type", "box plot per station");
      }
      if (index === 3) {
        // for boxplots don't show year selection
        this.$store.commit("selection/SET_CHART_TYPE", "BOX_MONTH");
        this.$store.commit("ui/SHOW_YEAR_SELECTION", false);
        this.$ga.event("Select", "Chart-Type", "box plot per month");
      }
    }
  }
};
</script>

<style lang="scss" scoped>
@import "../style/style.scss";
#chart-tabs {
  margin-left: 2rem;
}
#chart-tabs > div > div.ui.tab.segment.attached.active {
  background: $darkWhite;
}
</style>

// src/components/ChartsTabs/index.jsx
import React, { useState } from 'react'
import { Tab } from 'semantic-ui-react'
import ChartsLineChart from '../ChartsLineChart'
import ChartsBoxChartPerStation from '../ChartsBoxChartPerStation'
import ChartsBoxChartPerMonth from '../ChartsBoxChartPerMonth'
import useUiStore from '../../store/useUiStore'
import useSelectionStore from '../../store/useSelectionStore'
import './ChartsTabs.scss'

const ChartsTabs = ({ data, selection }) => {
  const [activeIndex, setActiveIndex] = useState(0)
  const ui = useUiStore()
  const selectionStore = useSelectionStore()

  const panes = [
    {
      menuItem: 'multi year line',
      render: () => (
        <Tab.Pane>
          <ChartsLineChart className="chart chart-spacer" selection={selection} data={data} />
        </Tab.Pane>
      )
    },
    {
      menuItem: 'single year line',
      render: () => (
        <Tab.Pane>
          <ChartsLineChart className="chart chart-spacer" selection={selection} data={data} />
        </Tab.Pane>
      )
    },
    {
      menuItem: 'box plot',
      render: () => (
        <Tab.Pane>
          <ChartsBoxChartPerStation className="chart chart-spacer" selection={selection} data={data} />
        </Tab.Pane>
      )
    },
    {
      menuItem: 'box plot per month',
      render: () => (
        <Tab.Pane>
          <ChartsBoxChartPerMonth className="chart chart-spacer" selection={selection} data={data} />
        </Tab.Pane>
      )
    }
  ]

  const handleTabChange = (e, { activeIndex }) => {
    setActiveIndex(activeIndex)
    if (activeIndex === 0) {
      selectionStore.setSingleYearSelection(false)
      selectionStore.setChartType('LINE_MULTI')
      selectionStore.setYearRange([data.startYear, data.endYear])
      ui.setShowYearSelection(true)
    } else if (activeIndex === 1) {
      selectionStore.setSingleYearSelection(true)
      selectionStore.setChartType('LINE_SINGLE')
      selectionStore.setYearRange([data.endYear, data.endYear])
      ui.setShowYearSelection(true)
    } else if (activeIndex === 2) {
      selectionStore.setChartType('BOX')
      ui.setShowYearSelection(false)
    } else if (activeIndex === 3) {
      selectionStore.setChartType('BOX_MONTH')
      ui.setShowYearSelection(false)
    }
  }

  return (
    <div id="chart-tabs">
      {selection.activeParam && (
        <Tab panes={panes} activeIndex={activeIndex} onTabChange={handleTabChange} />
      )}
    </div>
  )
}

export default ChartsTabs
