// src/components/DataTable.vue
<template>
  <div v-if="data.selectedStation"
       id="table">
    <div class="ui segment"
         s>
      <h3 is="sui-header"
          id="step-9"
          textAlign="center">{{data.selectedStation.info.StationName}}</h3>

      <v-client-table :data="tableData"
                      :columns="columns"
                      :options="options"></v-client-table>
    </div>
  </div>
</template>

<script>
import uniq from "lodash/uniq";
import { mapState } from "vuex";
import remove from "lodash/remove";
import flatten from "lodash/flatten";

export default {
  name: "DataTable",
  computed: {
    ...mapState({
      data: state => state.data,
      selection: state => state.selection
    }),
    columns: function() {
      let temp =
        (this.data &&
          this.data.selectedStation &&
          this.data.selectedStation.meta &&
          this.data.selectedStation.meta.params) ||
        [];

      temp = uniq(temp);
      
      if (!temp.includes("date")) {
        temp.unshift("date");
      }

      if (temp.includes("null_null")) {
        remove(temp, o => o === "null_null");
      }
      const obsRegex = RegExp("FieldObs_");
      temp = temp.filter(t => !obsRegex.test(t));
      const fieldRegex = RegExp("field_");
      temp = temp.filter(t => !fieldRegex.test(t));

      //temp = temp.sort();

      return temp;
    },
    tableData: function() {
      let rawData =
        (this.data &&
          this.data.selectedStation &&
          this.data.selectedStation.data) ||
        [];
      let data = [];
      // Build up all years data
      rawData.map(d => {
        let fields = {};
        Object.keys(d.results).map(k => {
          fields[k] = d.results[k].mean;
        });
        fields.date = d.date;
        if (fields.date.length > 0) {
          data.push(fields);
        }
      });
      // Reduce by selectionRange
      let start = this.selection.selectionRange[0];
      let end = this.selection.selectionRange[1];
      let selectedYearData = [];
      data.map(d => {
        let year = new Date(d.date).getFullYear();
        if (d.date && year >= start && year <= end) {
          selectedYearData.push(d);
        }
      });
      return selectedYearData;
    }
  },
  data: function() {
    return {
      options: {
        filterable: false,
        pagination: {
          dropdown: false
        },
        // see the options API
        perPage: 25
        // TODO: sort icon
      }
    };
  }
};
</script>

<style lang="scss">
@import "~bootstrap/scss/bootstrap";
#table {
  td {
    padding: 2px 5px;
  }
  margin-bottom: 1rem;
}
</style>

// src/components/DataTable/index.jsx
import React, { useMemo } from 'react'
import { Segment, Header } from 'semantic-ui-react'
import uniq from 'lodash/uniq'
import remove from 'lodash/remove'
import useDataStore from '../../store/useDataStore'
import useSelectionStore from '../../store/useSelectionStore'
import './DataTable.scss'

const DataTable = () => {
  const data = useDataStore()
  const selection = useSelectionStore()

  const columns = useMemo(() => {
    let temp = data.selectedStation?.meta?.params || []
    temp = uniq(temp)
    if (!temp.includes('date')) {
      temp.unshift('date')
    }
    remove(temp, (o) => o === 'null_null')
    const obsRegex = /FieldObs_/
    temp = temp.filter((t) => !obsRegex.test(t))
    const fieldRegex = /field_/
    temp = temp.filter((t) => !fieldRegex.test(t))
    return temp
  }, [data.selectedStation])

  const tableData = useMemo(() => {
    const station = data.selectedStation
    const rawData = station?.data || []
    const start = selection.selectionRange?.[0]
    const end = selection.selectionRange?.[1]

    const processedData = rawData.map((d) => {
      let fields = { date: d.date }
      Object.keys(d.results).forEach((k) => {
        fields[k] = d.results[k].mean
      })
      return fields
    })

    if (start && end) {
      return processedData.filter((d) => {
        const year = new Date(d.date).getFullYear()
        return year >= start && year <= end
      })
    }
    return processedData
  }, [data.selectedStation, selection.selectionRange])

  if (!data.selectedStation) return null

  return (
    <div id="table">
      <Segment>
        <Header as="h3" textAlign="center" id="step-9">
          {data.selectedStation.info.StationName}
        </Header>
        <div className="table-container">
          <table className="ui celled table">
            <thead>
              <tr>
                {columns.map((col) => (
                  <th key={col}>{col}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tableData.slice(0, 25).map((row, i) => (
                <tr key={i}>
                  {columns.map((col) => (
                    <td key={col}>{row[col]}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
          {tableData.length > 25 && <p>Showing first 25 rows...</p>}
        </div>
      </Segment>
    </div>
  )
}

export default DataTable
